repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        -   id: check-case-conflict
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: requirements-txt-fixer
        -   id: trailing-whitespace
        -   id: check-added-large-files
        -   id: debug-statements

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args:
        - "--max-line-length=135"
        - "--ignore=E701"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
